### PR TITLE
BUG 2102511: Fix hardcoded logic by filtering to expected file name.

### LINKED ISSUE #60: Error: 99-master-generated-kubelet: invalid character 'N' looking for beginning of
Compliance Operator reports an error while trying to parse the existing generated kubelet MachineConfig. We make use of a KubeletConfig with `autoSizingReserved: true` set.

```
{"level":"info","ts":1656537150.8045056,"logger":"suitectrl","msg":"Pausing pool","Request.Namespace":"openshift-compliance","Request.Name":"rhcos4","MachineConfigPool.Name":"worker"}
{"level":"info","ts":1656537150.85664,"logger":"suitectrl","msg":"All scans are in Done phase. Post-processing remediations","Request.Namespace":"openshift-compliance","Request.Name":"rhcos4"}
{"level":"error","ts":1656537150.8568845,"logger":"suitectrl","msg":"Retriable error","Request.Namespace":"openshift-compliance","Request.Name":"rhcos4","error":"failed to check if kubeletconfig auto-size-system-reserved-master is subset of rendered MC 99-master-generated-kubelet: invalid character 'N' looking for beginning of value","stacktrace":"github.com/openshift/compliance-operator/pkg/controller/compliancesuite.(*ReconcileComplianceSuite).Reconcile\n\t/remote-source/app/pkg/controller/compliancesuite/compliancesuite_controller.go:181\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1656537150.856978,"logger":"controller","msg":"Reconciler error","controller":"compliancesuite-controller","name":"rhcos4","namespace":"openshift-compliance","error":"failed to check if kubeletconfig auto-size-system-reserved-master is subset of rendered MC 99-master-generated-kubelet: invalid character 'N' looking for beginning of value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.11/pkg/util/wait/wait.go:90"}
{"level":"info","ts":1656538150.8576,"logger":"suitectrl","msg":"Reconciling ComplianceSuite","Request.Namespace":"openshift-compliance","Request.Name":"rhcos4"}
```

### PR DESCRIPTION
**Pull request by montaguethomas**
It is possible that KubeletConfigs will render more than just a single file in the generated MachineConfig objects. Currently the Compliance Operator is hardcoded to select the first file expecting it to be the `kubelet.conf` file. This is _not_ always the case.

This change uses a jsonpath filter to select the desired `/etc/kubernetes/kubelet.conf` file's contents. Fixes #60 

For example, when setting `autoSizingReserved: true` in a KubeletConfig, it will generate a MachineConfig like this:

```
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain,NODE_SIZING_ENABLED%3Dtrue%0ASYSTEM_RESERVED_MEMORY%3D1Gi%0ASYSTEM_RESERVED_CPU%3D500m%0A
        mode: 420
        overwrite: true
        path: /etc/node-sizing-enabled.env
      - contents:
          source: data:text/plain,TRUNCATED
        mode: 420
        overwrite: true
        path: /etc/kubernetes/kubelet.conf
  extensions: null
  fips: false
  kernelArguments: null
  kernelType: ""
  osImageURL: ""
```

### CODE REVIEW

**Comment by Vincent056** [comment]
Hi, could you change the path to `$.storage.files[? @.path=="/etc/kubernetes/kubelet.conf"].contents.source`?

File: pkg/utils/nodeutils.go [hunk 1]
```diff
@@ -152,11 +152,16 @@ func AreKubeletConfigsRendered(pool *mcfgv1.MachineConfigPool, client runtimecli
...
-	encodedKC, err := jsonpath.Get("storage.files[0].contents.source", obj)
+	// Filter to kubelet.conf file as other files (e.g. /etc/node-sizing-enabled.env) can exist.
+	encodedKC, err := jsonpath.Get(`$.storage.files[?(@.path == "/etc/kubernetes/kubelet.conf")].contents.source`, obj)
 	if err != nil {
 		return false, fmt.Errorf("failed to get encoded kubelet config from machine config %s: %w", currentKCMCName, err), diffString
 	}
-	encodedKCStr := encodedKC.(string)
+	encodedKCSlice := encodedKC.([]interface{})
+	if len(encodedKCSlice) == 0 {
+		return false, fmt.Errorf("encoded kubeletconfig %s is missing", currentKCMCName), diffString
```
Comment (Vincent056) [inline pkg/utils/nodeutils.go:162]: Maybe it is not a good idea to error out here? Because it can just be that KubletConfig is not yet fully rendered?
Could you put the error in `diffString`? Thanks

Comment (montaguethomas) [reply pkg/utils/nodeutils.go]: This is following the same logic when the kubelet.conf content is empty.

https://github.com/ComplianceAsCode/compliance-operator/pull/58/files#diff-dcf83ae774b84f0efb1bb9e9557214ab3d19130b89db9ea1107f60c084e002c9L161

**Comment by montaguethomas** [comment]
> Hi @montaguethomas thanks for the PR, could you change the path to `$.storage.files[? @.path=="/etc/kubernetes/kubelet.conf"].contents.source`?

Assuming you wanted the spaces removed from the filter. This is reverted back.

Resolving the test failures. Also broke out the core logic for the subset check into a dedicated function in order to implement more isolated tests. Added a bunch of tests.

**Review by Vincent056 — COMMENTED** [review]
Thanks for fixing the PR! I think it looks good to me, let's wait to see if e2e test pass

**Review by Vincent056 — APPROVED** [review]
/lgtm
